apiVersion: v1
kind: Pod
metadata:
  name: oom-killer-demo
spec:
  restartPolicy: Never
  containers:
    - name: memory-hog
      image: polinux/stress
      resources:
        requests:
          memory: "20Mi"
        limits:
          memory: "50Mi"
      command:
        - stress
      args:
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "200M"
        - "--vm-hang"
        - "1"